import { ISection } from './types';

const sections: ISection[] = [
  // {
  //   chapter: 'Summary of clinical findings in the patient (free text)',
  //   features: [],
  //   slug: 'summary-of-clinical-findings-in-the-patient',
  // },
  // { chapter: 'Photographs', features: [], slug: 'photographs' },
  // { chapter: 'Growth chart', features: [], slug: 'growth-chart' },
  // {
  //   chapter: 'Genetic investigations',
  //   features: [],
  //   slug: 'genetic-investigations',
  // },
  // { chapter: 'Radiology - imaging', features: [], slug: 'radiology-imaging' },
  // {
  //   chapter: 'Other investigations',
  //   features: [],
  //   slug: 'other-investigations',
  // },
  // { chapter: 'Pedigree', features: [], slug: 'pedigree' },
  // { chapter: 'Family history', features: [], slug: 'family-history' },
  {
    chapter: 'Pregnancy',
    features: [
      { term: 'HP:0001562', label: 'Oligohydramnios' },
      { term: 'HP:0001561', label: 'Polyhydramnios' },
      { term: 'HP:0011436', label: 'Abnormal maternal serum screening' },
      { term: 'HP:0034058', label: 'Abnormal fetal morphology' },
      { term: 'HP:0011425', label: 'Fetal ultrasound soft marker' },
      { term: 'HP:0034059', label: 'Abnormal fetal physiology' },
      { term: 'HP:0001511', label: 'Intrauterine growth retardation' },
      { term: 'HP:0003517', label: 'Fetal overgrowth' },
      { term: 'HP:0001558', label: 'Decreased fetal movement' },
      { term: 'HP:0010519', label: 'Increased fetal movement' },
      {
        term: 'HP:0001194',
        label: 'Abnormalities of placenta or umbilical cord',
      },
      {
        term: 'HP:0002686',
        label:
          'Prenatal maternal (health) abnormality (Describe in Clinical summary above)',
      },
      { term: 'HP:0030246', label: 'Maternal first trimester fever' },
      { term: 'HP:0009800', label: 'Maternal diabetes' },
      {
        term: 'HP:0011437',
        label:
          'Maternal autoimmune disease (Describe in Clinical summary above)',
      },
      { term: 'HP:0100622', label: 'Maternal seizure (during pregnancy)' },
      {
        term: 'HP:0011438',
        label:
          'Maternal teratogenic exposure (Describe in Clinical summary above)',
      },
      { term: 'HP:0100603', label: 'Toxemia of pregnancy' },
      {
        term: 'HP:0200067',
        label: 'Recurrent spontaneous abortion in previous pregnancies',
      },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'pregnancy',
  },
  {
    chapter: 'Delivery',
    features: [
      { term: 'HP:0001787', label: 'Abnormal delivery' },
      { term: 'HP:0025116', label: 'Fetal distress' },
      { term: 'HP:0030917', label: 'Low APGAR score' },
      { term: 'HP:0011410', label: 'Caesarian section' },
      { term: 'HP:0011411', label: 'Forceps delivery' },
      { term: 'HP:0011412', label: 'Ventouse delivery' },
      { term: 'HP:0001623', label: 'Breech presentation' },
      {
        term: 'HP:0012498',
        label: "Nuchal cord/Umbilical cord wrapped around the baby's neck",
      },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'delivery',
  },
  {
    chapter: 'Neonatal period complications',
    features: [
      { term: 'HP:0002643', label: 'Neonatal respiratory distress' },
      { term: 'HP:0008872', label: 'Feeding difficulties in infancy' },
      { term: 'HP:0011471', label: 'Gastrostomy tube feeding in infancy' },
      {
        term: 'HP:0000952',
        label: 'Significant jaundice (e.g., requiring treatment)',
      },
      { term: 'HP:0001998', label: 'Neonatal hypoglycemia' },
      { term: 'HP:0032807', label: 'Neonatal seizure' },
      { term: 'HP:0001319', label: 'Neonatal hypotonia' },
      { term: 'HP:0032169', label: 'Severe infection' },
      { term: 'HP:0002803', label: 'Congenital contracture' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'neonatal-period-complications',
  },
  {
    chapter: 'Growth at birth',
    features: [
      { term: 'HP:0001507', label: 'Growth abnormality at birth' },
      { term: 'HP:0001518', label: 'Small for gestational age' },
      { term: 'HP:0001520', label: 'Large for gestational age' },
      { term: 'HP:0000256', label: 'Macrocephaly' },
      { term: 'HP:0000252', label: 'Microcephaly' },
      { term: 'HP:0001528', label: 'Hemihypertrophy' },
      { term: 'HP:0000158', label: 'Macroglossia' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'growth-at-birth',
  },
  {
    chapter: 'Post-natal growth',
    features: [
      { term: 'HP:0001507', label: 'Abnormal growth' },
      { term: 'HP:0000256', label: 'Post-natal macrocephaly' },
      { term: 'HP:0000252', label: 'Post-natal microcephaly' },
      { term: 'HP:0000098', label: 'Tall stature' },
      { term: 'HP:0001519', label: 'Disproportionate tall stature' },
      { term: 'HP:0003498', label: 'Disproportionate short stature' },
      { term: 'HP:0004322', label: 'Short stature' },
      {
        term: 'HP:0008873',
        label: 'Disproportionate short-limb short stature',
      },
      {
        term: 'HP:0003521',
        label: 'Disproportionate short-trunk short stature',
      },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'post-natal-growth',
  },
  {
    chapter: 'Facial morphology',
    features: [
      { term: 'HP:0001999', label: 'Abnormal facial shape' },
      { term: 'HP:0000306', label: 'Abnormality of the chin' },
      { term: 'HP:0000347', label: 'Micrognathia' },
      { term: 'HP:0000277', label: 'Abnormal mandible morphology' },
      { term: 'HP:0000326', label: 'Abnormality of the maxilla' },
      { term: 'HP:0000290', label: 'Abnormality of the forehead' },
      { term: 'HP:0011220', label: 'Prominent forehead' },
      { term: 'HP:0000340', label: 'Sloping forehead' },
      { term: 'HP:0000520', label: 'Proptosis' },
      { term: 'HP:0000316', label: 'Hypertelorism' },
      { term: 'HP:0000601', label: 'Hypotelorism' },
      { term: 'HP:0000492', label: 'Abnormal eyelid morphology' },
      { term: 'HP:0008050', label: 'Abnormality of the palpebral fissures' },
      { term: 'HP:0000286', label: 'Epicanthus' },
      { term: 'HP:0000506', label: 'Telecanthus' },
      { term: 'HP:0010938', label: 'Abnormality of the external nose' },
      { term: 'HP:0011800', label: 'Midface retrusion (Flat midface)' },
      { term: 'HP:0000154', label: 'Wide mouth' },
      { term: 'HP:0000160', label: 'Narrow mouth' },
      { term: 'HP:0012471', label: 'Thick vermilion border' },
      { term: 'HP:0000233', label: 'Thin vermilion border' },
      { term: 'HP:0000319', label: 'Smooth philtrum' },
      { term: 'HP:0000322', label: 'Short philtrum' },
      { term: 'HP:0000343', label: 'Long philtrum' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'facial-morphology',
  },
  {
    chapter: 'Eyes',
    features: [
      { term: 'HP:0000478', label: 'Abnormality of the eye' },
      { term: 'HP:0012372', label: 'Abnormal eye morphology' },
      { term: 'HP:0000525', label: 'Abnormal iris morphology' },
      { term: 'HP:0000505', label: 'Visual impairment' },
      { term: 'HP:0030669', label: 'Abnormal ocular adnexa morphology' },
      { term: 'HP:0000479', label: 'Abnormality of the retina' },
      { term: 'HP:0000501', label: 'Glaucoma' },
      { term: 'HP:0000486', label: 'Strabismus' },
      { term: 'HP:0000518', label: 'Cataract' },
      { term: 'HP:0000526', label: 'Aniridia' },
      { term: 'HP:0000589', label: 'Coloboma' },
      { term: 'HP:0000568', label: 'Microphthalmia' },
      { term: 'HP:0000639', label: 'Nystagmus' },
      { term: 'HP:0000508', label: 'Ptosis' },
      { term: 'HP:0000613', label: 'Photophobia' },
      { term: 'HP:0000587', label: 'Abnormality of the optic nerve' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'eyes',
  },
  {
    chapter: 'Mouth/teeth',
    features: [
      { term: 'HP:0000163', label: 'Abnormal oral cavity morphology' },
      { term: 'HP:0000175', label: 'Cleft palate' },
      { term: 'HP:0410030', label: 'Cleft lip' },
      { term: 'HP:0000202', label: 'Cleft/palate' },
      { term: 'HP:0000168', label: 'Abnormality of the gingiva' },
      { term: 'HP:0000218', label: 'High palate' },
      { term: 'HP:0000164', label: 'Abnormality of the dentition' },
      { term: 'HP:0006483', label: 'Abnormal number of teeth' },
      { term: 'HP:0006482', label: 'Abnormal dental morphology' },
      { term: 'HP:0000682', label: 'Abnormal dental enamel morphology' },
      { term: 'HP:0000157', label: 'Abnormality of the tongue' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'mouthteeth',
  },
  {
    chapter: 'Nose',
    features: [
      { term: 'HP:0005105', label: 'Abnormal nasal morphology' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'nose',
  },
  {
    chapter: 'Ears',
    features: [
      { term: 'HP:0000407', label: 'Sensorineural hearing impairment' },
      { term: 'HP:0000405', label: 'Conductive hearing impairment' },
      { term: 'HP:0000377', label: 'Abnormality of the pinna' },
      { term: 'HP:0000369', label: 'Low-set ears' },
      { term: 'HP:0000400', label: 'Macrotia' },
      { term: 'HP:0008551', label: 'Microtia' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'ears',
  },
  {
    chapter: 'Central nervous system + neuromuscular system + cognition',
    features: [
      { term: 'HP:0000707', label: 'Abnormality of the nervous system' },
      { term: 'HP:0012443', label: 'Abnormality of brain morphology' },
      { term: 'HP:0002194', label: 'Delayed gross motor development' },
      { term: 'HP:0001263', label: 'Global developmental delay' },
      { term: 'HP:0001256', label: 'Intellectual disability, mild' },
      { term: 'HP:0002342', label: 'Intellectual disability, moderate' },
      { term: 'HP:0002187', label: 'Intellectual disability, profound' },
      { term: 'HP:0010864', label: 'Intellectual disability, severe' },
      { term: 'HP:0006887', label: 'Intellectual disability, progressive' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'central-nervous-system-neuromuscular-system-cognition',
  },
  {
    chapter: 'Behavioral abnormality',
    features: [
      { term: 'HP:0000729', label: 'Autistic behavior' },
      { term: 'HP:0007018', label: 'Attention deficit hyperactivity disorder' },
      { term: 'HP:0100716', label: 'Self-injurious behavior' },
      { term: 'HP:0000718', label: 'Aggressive behavior' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'behavioral-abnormality',
  },
  {
    chapter: 'Speech',
    features: [
      { term: 'HP:0000750', label: 'Delayed speech and language development' },
      { term: 'HP:0002465', label: 'Poor speech' },
      { term: 'HP:0001344', label: 'Absent speech' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'speech',
  },
  {
    chapter: 'Seizures',
    features: [
      { term: 'HP:0001250', label: 'Seizure' },
      { term: 'HP:0032807', label: 'Neonatal seizure' },
      { term: 'HP:0002349', label: 'Focal aware seizure' },
      { term: 'HP:0002384', label: 'Focal impaired awareness seizure' },
      { term: 'HP:0002197', label: 'Generalized onset seizure' },
      { term: 'HP:0002353', label: 'EEG abnormality' },
      {
        term: 'other',
        label:
          'Other. Describe in Clinical summary and/or add HPO terms here. Please ensure in clinical summary that you include as much information as possible about age of onset, course of the disease, semiology, triggers, response to treatment, recurrent status, characteristic EEG patterning, brain imaging, abnormal metabolism, abnormal CSF etc.',
      },
    ],
    slug: 'seizures',
  },
  {
    chapter: 'Muscles',
    features: [
      { term: 'HP:0003011', label: 'Abnormality of the musculature' },
      { term: 'HP:0001324', label: 'Muscle weakness' },
      { term: 'HP:0003808', label: 'Abnormal muscle tone' },
      { term: 'HP:0001276', label: 'Hypertonia' },
      { term: 'HP:0001252', label: 'Hypotonia' },
      { term: 'HP:0001371', label: 'Flexion contracture' },
      { term: 'HP:0002804', label: 'Arthrogryposis multiplex congenita' },
      { term: 'HP:0003560', label: 'Muscular dystrophy' },
      { term: 'HP:0003457', label: 'EMG abnormality' },
      { term: 'HP:0011804', label: 'Abnormal muscle physiology' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'muscles',
  },
  {
    chapter: 'Skeleton',
    features: [
      { term: 'HP:0002652', label: 'Skeletal dysplasia' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'skeleton',
  },
  {
    chapter: 'Head and neck',
    features: [
      { term: 'HP:0000929', label: 'Abnormal skull' },
      { term: 'HP:0001363', label: 'Craniosynostosis' },
      { term: 'HP:0011329', label: 'Abnormality of cranial sutures' },
      { term: 'HP:0000470', label: 'Short neck' },
      { term: 'HP:0000475', label: 'Broad neck' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'head-and-neck',
  },
  {
    chapter: 'Trunk',
    features: [
      { term: 'HP:0000765', label: 'Abnormal thorax morphology' },
      { term: 'HP:0000925', label: 'Abnormality of the vertebral column' },
      { term: 'HP:0002650', label: 'Scoliosis' },
      { term: 'HP:0003272', label: 'Abnormal hip bone morphology' },
      { term: 'HP:0002827', label: 'Hip dislocation' },
      { term: 'HP:0000782', label: 'Abnormal scapula morphology' },
      { term: 'HP:0003043', label: 'Abnormal shoulder morphology' },
      { term: 'HP:0000766', label: 'Abnormal sternum morphology' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'trunk',
  },
  {
    chapter: 'Upper limbs',
    features: [
      { term: 'HP:0002817', label: 'Abnormality of the upper limb' },
      { term: 'HP:0002818', label: 'Abnormality of the radius' },
      { term: 'HP:0002997', label: 'Abnormality of the ulna' },
      { term: 'HP:0009811', label: 'Abnormality of the elbow' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'upper-limbs',
  },
  {
    chapter: 'Hands, fingers, and thumbs',
    features: [
      { term: 'HP:0000954', label: 'Single transverse palmar crease' },
      { term: 'HP:0001177', label: 'Preaxial hand polydactyly' },
      { term: 'HP:0100259', label: 'Postaxial hand polydactyly' },
      { term: 'HP:0001156', label: 'Brachydactyly' },
      { term: 'HP:0100807', label: 'Long fingers (Arachnodactyly)' },
      { term: 'HP:0100257', label: 'Cleft hand (Ectrodactyly)' },
      { term: 'HP:0006265', label: 'Aplasia/Hypoplasia of fingers' },
      { term: 'HP:0009601', label: 'Aplasia/Hypoplasia of thumb' },
      { term: 'HP:0011304', label: 'Broad thumb' },
      { term: 'HP:0001159', label: 'Syndactyly' },
      { term: 'HP:0004099', label: 'Macrodactyly' },
      { term: 'HP:0010557', label: 'Overlapping fingers' },
      { term: 'HP:0001212', label: 'Prominent fingertip pads' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'hands-fingers-and-thumbs',
  },
  {
    chapter: 'Lower limbs',
    features: [
      { term: 'HP:0002814', label: 'Abnormality of the lower limb' },
      { term: 'HP:0002992', label: 'Abnormality of tibia morphology' },
      { term: 'HP:0002991', label: 'Abnormality of fibula morphology' },
      { term: 'HP:0003045', label: 'Abnormality of the patella morphology' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'lower-limbs',
  },
  {
    chapter: 'Feet/toes',
    features: [
      { term: 'HP:0001830', label: 'Postaxial foot polydactyly' },
      { term: 'HP:0001841', label: 'Preaxial foot polydactyly' },
      { term: 'HP:0001831', label: 'Brachydactyly of the foot' },
      { term: 'HP:0010511', label: 'Long toe' },
      { term: 'HP:0010173', label: 'Aplasia/Hypoplasia of phalanges of toes' },
      { term: 'HP:0008110', label: 'Equinovarus deformity' },
      { term: 'HP:0001159', label: 'Syndactyly' },
      { term: 'HP:0010055', label: 'Broad hallux' },
      { term: 'HP:0010097', label: 'Bifid distal phalanx of hallux' },
      { term: 'HP:0001845', label: 'Overlapping toes' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'feettoes',
  },
  {
    chapter: 'Airways',
    features: [
      { term: 'HP:0010640', label: 'Abnormality of the nasal cavity' },
      { term: 'HP:0002778', label: 'Abnormal tracheal morphology' },
      { term: 'HP:0002088', label: 'Abnormal lung morphology' },
      { term: 'HP:0025423', label: 'Abnormal larynx morphology' },
      { term: 'HP:0006536', label: 'Airway obstruction' },
      { term: 'HP:0005957', label: 'Breathing dysregulation' },
      { term: 'HP:0002094', label: 'Dyspnea' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'airways',
  },
  {
    chapter: 'Heart/great vessels',
    features: [
      { term: 'HP:0001627', label: 'Abnormal heart morphology' },
      { term: 'HP:0001671', label: 'Abnormal cardiac septum morphology' },
      { term: 'HP:0001631', label: 'Atrial septal defect' },
      { term: 'HP:0001629', label: 'Ventricular septal defect' },
      { term: 'HP:0006695', label: 'Atrioventricular canal defect' },
      { term: 'HP:0001636', label: 'Tetralogy of Fallot' },
      { term: 'HP:0011675', label: 'Arrhythmia' },
      { term: 'HP:0001638', label: 'Cardiomyopathy' },
      { term: 'HP:0000822', label: 'Hypertension' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'heartgreat-vessels',
  },
  {
    chapter: 'Kidneys and urinary tract',
    features: [
      { term: 'HP:0000077', label: 'Abnormality of the kidneys' },
      { term: 'HP:0000104', label: 'Renal agenesis' },
      { term: 'HP:0000079', label: 'Abnormality of the urinary system' },
      { term: 'HP:0000107', label: 'Renal cysts' },
      { term: 'HP:0000105', label: 'Enlarged kidney' },
      { term: 'HP:0012211', label: 'Abnormal kidney function' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'kidneys-and-urinary-tract',
  },
  {
    chapter: 'Genitalia',
    features: [
      { term: 'HP:0000811', label: 'Abnormal external genitalia' },
      { term: 'HP:0000812', label: 'Abnormal internal genitalia' },
      { term: 'HP:0000028', label: 'Cryptorchidism' },
      { term: 'HP:0000047', label: 'Hypospadias' },
      { term: 'HP:0000062', label: 'Ambiguous genitalia' },
      { term: 'HP:0000078', label: 'Abnormality of genital system' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'genitalia',
  },
  {
    chapter: 'Liver and spleen',
    features: [
      { term: 'HP:0001392', label: 'Abnormality of the liver' },
      { term: 'HP:0001410', label: 'Decreased liver function' },
      { term: 'HP:0002240', label: 'Hepatomegaly' },
      { term: 'HP:0001407', label: 'Hepatic cysts' },
      { term: 'HP:0001743', label: 'Abnormality of the spleen' },
      { term: 'HP:0001744', label: 'Splenomegaly' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'liver-and-spleen',
  },
  {
    chapter: 'Skin',
    features: [
      { term: 'HP:0000951', label: 'Abnormality of the skin' },
      { term: 'HP:0001000', label: 'Abnormality of skin pigmentation' },
      { term: 'HP:0007565', label: 'Multiple cafe-au-lait spots' },
      { term: 'HP:0001480', label: 'Freckling (axillary or inguinal)' },
      { term: 'HP:0100669', label: 'Abnormal pigmentation of the oral mucosa' },
      { term: 'HP:0031447', label: 'Penile freckling' },
      { term: 'HP:0008066', label: 'Abnormal blistering of the skin' },
      { term: 'HP:0011276', label: 'Vascular skin abnormality' },
      { term: 'HP:0002745', label: 'Oral leucoplakia' },
      { term: 'HP:0002558', label: 'Supernumerary nipple' },
      { term: 'HP:0008069', label: 'Neoplasm of the skin' },
      { term: 'HP:0000958', label: 'Dry skin' },
      { term: 'HP:0000964', label: 'Eczema' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'skin',
  },
  {
    chapter: 'Hair/nails',
    features: [
      { term: 'HP:0001595', label: 'Abnormal hair morphology' },
      { term: 'HP:0002216', label: 'Premature greying of hair' },
      { term: 'HP:0000664', label: 'Synophrys' },
      { term: 'HP:0000534', label: 'Abnormal eyebrow morphology' },
      { term: 'HP:0001597', label: 'Abnormality of the nails' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'hairnails',
  },
  {
    chapter: 'Endocrine/metabolic',
    features: [
      { term: 'HP:0000819', label: 'Diabetes mellitus' },
      { term: 'HP:0001988', label: 'Recurrent hypoglycemia' },
      { term: 'HP:0004902', label: 'Congenital lactic acidosis' },
      { term: 'HP:0000821', label: 'Hypothyroidism' },
      { term: 'HP:0000828', label: 'Abnormality of the parathyroid gland' },
      {
        term: 'HP:0012093',
        label: 'Abnormality of endocrine pancreas physiology',
      },
      {
        term: 'HP:0000864',
        label: 'Abnormality of the hypothalamus-pituitary axis',
      },
      { term: 'HP:0000834', label: 'Abnormality of the adrenal glands' },
      { term: 'HP:0000826', label: 'Precocious puberty' },
      { term: 'HP:0000823', label: 'Delayed puberty' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'endocrinemetabolic',
  },
  {
    chapter: 'Connective tissue',
    features: [
      { term: 'HP:0001382', label: 'Joint hypermobility' },
      { term: 'HP:0001763', label: 'Pes planus' },
      { term: 'HP:0001373', label: 'Joint dislocation' },
      { term: 'HP:0000978', label: 'Bruising susceptibility' },
      { term: 'HP:0001030', label: 'Fragile skin' },
      { term: 'HP:0001065', label: 'Striae distensae' },
      { term: 'HP:0002617', label: 'Aneurysm (Vascular dilatation)' },
      { term: 'HP:0100790', label: 'Hernia' },
      { term: 'HP:0008067', label: 'Abnormally lax or hyperextensible skin' },
      { term: 'HP:0000973', label: 'Cutis laxa' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'connective-tissue',
  },
  {
    chapter: 'Immune system/blood',
    features: [
      { term: 'HP:0004313', label: 'Decreased circulating antibody level' },
      { term: 'HP:0002960', label: 'Autoimmunity' },
      { term: 'HP:0012647', label: 'Abnormal inflammatory response' },
      { term: 'HP:0001903', label: 'Anemia' },
      { term: 'HP:0001882', label: 'Leukopenia' },
      { term: 'HP:0001873', label: 'Thrombocytopenia' },
      { term: 'HP:0001929', label: 'Abnormality of coagulation' },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'immune-systemblood',
  },
  {
    chapter: 'Gastrointestinal',
    features: [
      { term: 'HP:0002608', label: 'Celiac disease' },
      { term: 'HP:0002013', label: 'Vomiting' },
      { term: 'HP:0002020', label: 'Gastroesophageal reflux' },
      { term: 'HP:0002014', label: 'Diarrhea' },
      { term: 'HP:0002019', label: 'Constipation' },
      { term: 'HP:0011968', label: 'Feeding difficulties' },
      { term: 'HP:0002015', label: 'Dysphagia' },
      {
        term: 'HP:0012718',
        label: 'Morphological abnormality of the gastrointestinal tract',
      },
      {
        term: 'other',
        label: 'Other. Describe in Clinical summary and/or add HPO terms here',
      },
    ],
    slug: 'gastrointestinal',
  },
  {
    chapter: 'Cancer/malignancy /benign tumor',
    features: [
      { term: 'HP:0002664', label: 'Neoplasm (Benign or malignant)' },
      { term: 'HP:0004377', label: 'Hematological neoplasm' },
      {
        term: 'other',
        label:
          'Please specify the type of cancer/malignancy/benign tumor and age at diagnosis in the section of Summary of clinical findings above and provide HPO terms',
      },
    ],
    slug: 'cancermalignancy-benign-tumor',
  },
];

export default sections;
